name = "IteratedExtendedKalmanFilter"
uuid = "6b1ba58f-f9b7-4118-bdf7-3b7e0498e03f"
authors = ["Jakub Kaspar"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Enzyme = "0.13"
BenchmarkTools = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
